import Navbar from "@/app/_components/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0, backgroundColor: "white", fontFamily: "Arial, sans-serif" }}>
        <Navbar />
        <main style={{ padding: "2rem", maxWidth: "1200px", margin: "0 auto" }}>
          <Suspense>
            {children}
          </Suspense>

        </main>
      </body>
    </html>
  );
}
